// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pinger} from '../models';

export function AddDestination(arg1:string):Promise<void>;

export function IgnoreMe(arg1:pinger.PingEvent):Promise<void>;

export function RemoveDestination(arg1:string):Promise<void>;
