// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDestination(arg1) {
  return window['go']['main']['App']['AddDestination'](arg1);
}

export function IgnoreMe(arg1) {
  return window['go']['main']['App']['IgnoreMe'](arg1);
}

export function RemoveDestination(arg1) {
  return window['go']['main']['App']['RemoveDestination'](arg1);
}
